# Setup
title:               The Reviews 
tagline:             
description:         'The reviews is a product reviewing site which will give you the quality information form variety of products like electronics, accessories, gadgets   etc for your favourite brands'  
url:                 https://thereviews.github.io 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:             
  url:               
  email:             
  
  
  social-network-links:
  email: "someone@example.com"
  
  

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
